### ISSUE TITLE
feature request: connection pooling

### ISSUE THREAD

**Issue by Nymphium** [roburio/http-lwt-client#9]

**Comment by hannesm** [comment]
Thanks for your feature request, would you mind to elaborate which connection you would like to pool and where and why?

**Comment by Nymphium** [comment]
I'm trying to communicate with a HTTPS service, but every requests needs TLS/SSL authentitacion with this library currently. This is very overhead, so pooling HTTP connections is needed.

**Comment by hannesm** [comment]
Thanks for your explanation. Maybe it makes sense to expose an API where the connection is already established (with HTTP1 / HTTP2). My fear is that the complexity will be increased tremendously.

But please feel free to take inspiration from this library, work on that feature and open a pull request. It will be considered (though - as mentioned above, if it turns out to include a lot of complexity, it might be out of scope for this library).

**Comment by Nymphium** [comment]
I found the another overhead that naively call `one_request` creates happy eyeballs instance and tls config. It would be better if these parameters is cached with given uri.

**Comment by hannesm** [comment]
> naively call `one_request` creates happy eyeballs instance and tls config
> It would be better if these parameters is cached with given uri.

you can do so, and pass happy eyeballs and tls_config as arguments (they are optional and labelled). You shouldn't use any API naively.

I'll close this, since it is out of scope for this little project.
